### ISSUE TITLE
Refactor POST /User route

### ISSUE THREAD

**Issue by dpopp07** [bartop-io/bartop#106]
Thinking more about it, I think that using a URL parameter in a `POST` request is weird and we should be using a request body. Not that this is necessarily _bad_ practice (I can't think of any huge downsides) but it is just not standard practice and is probably not good UX for API design.

Another thought: To maximize efficiency of DB operations, it may be a good idea to not use the user's ID as the primary key in the users table (which is happening right now). I'm not sure about this but I feel like indexing will be faster if we use Rethink-generated GUIDs and store the user id as a separate value. I'll look into this more.

@jamesvclements thoughts on these?

Also, I want to validate the user id to ensure that it matches the Auth0 format.

Also, I want this route to be protected differently than others. If this ever becomes a public API, this is still a route only our app should have access to. This is probably out of the scope of this issue though.

**todo**
- [x] Change endpoint to parse request body and remove the id URL parameter
- [x] Don't use user id as primary key
~~Add a validation step for the format of the id~~ We decided against this
- [x] Add validation for the entire user body
