### ISSUE TITLE
Bartender creating their catalog

### ISSUE THREAD

**Issue by dpopp07** [bartop-io/bartop#115]
This will require:

- [ ] Designing a UX flow for how they do it (wizard or not, etc.)
- [ ] Designing/implementing the UI for creating a catalog and adding drinks to it
- [ ] API endpoints for creating a catalog and updating catalogs with new creating
